language: python
services:
  - sqlite
cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
matrix:
    include:
      - python: 2.7
        env: TOX_ENV=py27-django111
      - python: 3.6
        env: TOX_ENV=py36-django111
      - python: 3.6
        env: TOX_ENV=py36-django22
      - python: 3.6
        env: TOX_ENV=py36-django30
      - python: 3.7
        env: TOX_ENV=py37-django111
      - python: 3.7
        env: TOX_ENV=py37-django22
      - python: 3.7
        env: TOX_ENV=py37-django30
      - python: 3.8
        env: TOX_ENV=py38-django111
      - python: 3.8
        env: TOX_ENV=py38-django22
      - python: 3.8
        env: TOX_ENV=py38-django30
 #including ppc64le to run on power systems  
      - python: 2.7
        arch: ppc64le
        env: TOX_ENV=py27-django111
      - python: 3.6
        arch: ppc64le
        env: TOX_ENV=py36-django111
      - python: 3.6
        arch: ppc64le
        env: TOX_ENV=py36-django22
      - python: 3.6
        arch: ppc64le
        env: TOX_ENV=py36-django30
      - python: 3.7
        arch: ppc64le
        env: TOX_ENV=py37-django111
      - python: 3.7
        arch: ppc64le
        env: TOX_ENV=py37-django22
      - python: 3.7
        arch: ppc64le
        env: TOX_ENV=py37-django30
      - python: 3.8
        arch: ppc64le
        env: TOX_ENV=py38-django111
      - python: 3.8
        arch: ppc64le
        env: TOX_ENV=py38-django22
      - python: 3.8
        arch: ppc64le
        env: TOX_ENV=py38-django3
# excluding versions of python
# Disable version 3.7, 3.8
jobs: 
  exclude:
      - python: 3.7
        arch: ppc64le
        env: TOX_ENV=py37-django111
      - python: 3.7
        env: TOX_ENV=py37-django111
      - python: 3.7
        arch: ppc64le
        env: TOX_ENV=py37-django22
      - python: 3.7
        env: TOX_ENV=py37-django22
      - python: 3.7
        arch: ppc64le
        env: TOX_ENV=py37-django30
      - python: 3.7
        env: TOX_ENV=py37-django30
      - python: 3.8
        arch: ppc64le
        env: TOX_ENV=py38-django111
      - python: 3.8
        env: TOX_ENV=py38-django111
      - python: 3.8
        arch: ppc64le
        env: TOX_ENV=py38-django22
      - python: 3.8
        env: TOX_ENV=py38-django22
      - python: 3.8
        arch: ppc64le
        env: TOX_ENV=py38-django30
      - python: 3.8
        arch: ppc64le
        env: TOX_ENV=py38-django30
		
script: tox -e $TOX_ENV
install:
    - pip install pip setuptools wheel -U
    - pip install tox tox-travis
